# Generated by Django 2.0.10 on 2019-01-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('is_due_today', models.BooleanField(default=False)),
                ('is_due_tomorrow', models.BooleanField(default=False)),
            ],
        ),
    ]
